// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: claim.
// - Entity ID: 102019b9b7367bd7044af70c84ea321eb0b.
// - Entity Version: 102019b9b810e8371519eb84110a2b594e9.
// - Task ID: 695f1acd08da5b90fa0c4f03.
// - Task Root ID: 695f17652d44c5a3bf62520b.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ClaimClaimStatus
 */
export enum ClaimClaimStatus {
  Unspecified = 0,
  Pending = 1,
  Approved = 2,
  Declined = 3,
}



/**
 * Interface for ClaimModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ClaimModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  item_id: string;
  student_name: string;
  student_id: string;
  student_email: string;
  grade: string;
  homeroom_teacher: string;
  pickup_time_slot: string;
  claim_status: ClaimClaimStatus;
}

/**
 * ORM class for Claim entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ClaimORM {
  private static instance: ClaimORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b9b7367bd7044af70c84ea321eb0b';
    this.entityName = 'claim';
    this.entityVersion = '102019b9b810e8371519eb84110a2b594e9';
    this.taskId = '695f1acd08da5b90fa0c4f03';
    this.taskRootId = '695f17652d44c5a3bf62520b';
  }

  /**
   * Get singleton instance of ClaimORM
   */
  public static getInstance(): ClaimORM {
    if (!ClaimORM.instance) {
      ClaimORM.instance = new ClaimORM();
    }
    
    return ClaimORM.instance;
  }

  /**
   * Get claim by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getClaimByIDs(ids: string[]): Promise<ClaimModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteClaimByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Claim records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllClaim(): Promise<ClaimModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Claim record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertClaim(data: ClaimModel[]): Promise<ClaimModel[]> {
    const structured = data.map((item) => CreateData(ClaimModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Claim records
   */
  async purgeAllClaim(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Claim records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listClaim(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ClaimModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get claim by Id index
   * This function gets data by index.
   */
  async getClaimById(
    id: string,
  ): Promise<ClaimModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) claim by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClaimById(
    id: string,
    data: ClaimModel
  ): Promise<ClaimModel[]> {
    const index = createIndexId(
      id
    );

    const values = ClaimModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by Id index
   */
  async deleteClaimById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get claim by DataCreator index
   * This function gets data by index.
   */
  async getClaimByDataCreator(
    data_creator: string,
  ): Promise<ClaimModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) claim by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClaimByDataCreator(
    data_creator: string,
    data: ClaimModel
  ): Promise<ClaimModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ClaimModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by DataCreator index
   */
  async deleteClaimByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get claim by DataUpdater index
   * This function gets data by index.
   */
  async getClaimByDataUpdater(
    data_updater: string,
  ): Promise<ClaimModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) claim by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClaimByDataUpdater(
    data_updater: string,
    data: ClaimModel
  ): Promise<ClaimModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ClaimModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by DataUpdater index
   */
  async deleteClaimByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get claim by ItemId index
   * This function gets data by index.
   */
  async getClaimByItemId(
    item_id: string,
  ): Promise<ClaimModel[]> {
    const index = createIndexItemId(
      item_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) claim by ItemId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClaimByItemId(
    item_id: string,
    data: ClaimModel
  ): Promise<ClaimModel[]> {
    const index = createIndexItemId(
      item_id
    );

    const values = ClaimModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by ItemId index
   */
  async deleteClaimByItemId(
    item_id: string
  ): Promise<void> {
    const index = createIndexItemId(
      item_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get claim by StudentId index
   * This function gets data by index.
   */
  async getClaimByStudentId(
    student_id: string,
  ): Promise<ClaimModel[]> {
    const index = createIndexStudentId(
      student_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) claim by StudentId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClaimByStudentId(
    student_id: string,
    data: ClaimModel
  ): Promise<ClaimModel[]> {
    const index = createIndexStudentId(
      student_id
    );

    const values = ClaimModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by StudentId index
   */
  async deleteClaimByStudentId(
    student_id: string
  ): Promise<void> {
    const index = createIndexStudentId(
      student_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get claim by ClaimStatus index
   * This function gets data by index.
   */
  async getClaimByClaimStatus(
    claim_status: ClaimClaimStatus,
  ): Promise<ClaimModel[]> {
    const index = createIndexClaimStatus(
      claim_status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) claim by ClaimStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setClaimByClaimStatus(
    claim_status: ClaimClaimStatus,
    data: ClaimModel
  ): Promise<ClaimModel[]> {
    const index = createIndexClaimStatus(
      claim_status
    );

    const values = ClaimModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete claim by ClaimStatus index
   */
  async deleteClaimByClaimStatus(
    claim_status: ClaimClaimStatus
  ): Promise<void> {
    const index = createIndexClaimStatus(
      claim_status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ClaimModel data array
   */
  private resultToData(values: Data[]): ClaimModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ClaimModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ClaimModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ClaimModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ClaimModel => item !== null);
  }
}

/**
 * Convert ClaimModel data to Value array
 */
function ClaimModelToValues(data: ClaimModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'item_id', type: DataType.string, defaultValue: '' },
    { key: 'student_name', type: DataType.string, defaultValue: '' },
    { key: 'student_id', type: DataType.string, defaultValue: '' },
    { key: 'student_email', type: DataType.string, defaultValue: '' },
    { key: 'grade', type: DataType.string, defaultValue: '' },
    { key: 'homeroom_teacher', type: DataType.string, defaultValue: '' },
    { key: 'pickup_time_slot', type: DataType.string, defaultValue: '' },
    { key: 'claim_status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ClaimModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ClaimModel data
 */
function ClaimModelFromValues(values: Value[]): ClaimModel {
  const data: Partial<ClaimModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'item_id':
        data.item_id = ParseValue(value, DataType.string) as string;
        break;
      case 'student_name':
        data.student_name = ParseValue(value, DataType.string) as string;
        break;
      case 'student_id':
        data.student_id = ParseValue(value, DataType.string) as string;
        break;
      case 'student_email':
        data.student_email = ParseValue(value, DataType.string) as string;
        break;
      case 'grade':
        data.grade = ParseValue(value, DataType.string) as string;
        break;
      case 'homeroom_teacher':
        data.homeroom_teacher = ParseValue(value, DataType.string) as string;
        break;
      case 'pickup_time_slot':
        data.pickup_time_slot = ParseValue(value, DataType.string) as string;
        break;
      case 'claim_status':
        data.claim_status = ParseValue(value, DataType.enumeration) as ClaimClaimStatus;
        break;
    }
  }
  
  return data as ClaimModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ItemId fields
 */
function createIndexItemId(
  item_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, item_id, 'item_id'),
  ];

  return {
    fields: ['item_id'],
    values
  };
}
/**
 * Create index for StudentId fields
 */
function createIndexStudentId(
  student_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, student_id, 'student_id'),
  ];

  return {
    fields: ['student_id'],
    values
  };
}
/**
 * Create index for ClaimStatus fields
 */
function createIndexClaimStatus(
  claim_status: ClaimClaimStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, claim_status, 'claim_status'),
  ];

  return {
    fields: ['claim_status'],
    values
  };
}

export default ClaimORM;