// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: lost_item.
// - Entity ID: 102019b9b7367bd7297884f66762a0d4395.
// - Entity Version: 102019b9b810e8371519eb84110a2b594e9.
// - Task ID: 695f1acd08da5b90fa0c4f03.
// - Task Root ID: 695f17652d44c5a3bf62520b.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for LostItemCategory
 */
export enum LostItemCategory {
  Unspecified = 0,
  Electronics = 1,
  Books = 2,
  Clothing = 3,
  Accessories = 4,
  Keys = 5,
  Bags = 6,
  SportsEquipment = 7,
  Miscellaneous = 8,
}
/**
 * Enumeration for LostItemStatus
 */
export enum LostItemStatus {
  Unspecified = 0,
  Pending = 1,
  Active = 2,
  Claimed = 3,
}



/**
 * Interface for LostItemModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface LostItemModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  photo_url?: string | null;
  item_name: string;
  description?: string | null;
  category: LostItemCategory;
  date_found: string;
  location_found: string;
  finder_name?: string | null;
  finder_email?: string | null;
  status: LostItemStatus;
}

/**
 * ORM class for LostItem entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class LostItemORM {
  private static instance: LostItemORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b9b7367bd7297884f66762a0d4395';
    this.entityName = 'lost_item';
    this.entityVersion = '102019b9b810e8371519eb84110a2b594e9';
    this.taskId = '695f1acd08da5b90fa0c4f03';
    this.taskRootId = '695f17652d44c5a3bf62520b';
  }

  /**
   * Get singleton instance of LostItemORM
   */
  public static getInstance(): LostItemORM {
    if (!LostItemORM.instance) {
      LostItemORM.instance = new LostItemORM();
    }
    
    return LostItemORM.instance;
  }

  /**
   * Get lost_item by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getLostItemByIDs(ids: string[]): Promise<LostItemModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteLostItemByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all LostItem records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllLostItem(): Promise<LostItemModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new LostItem record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertLostItem(data: LostItemModel[]): Promise<LostItemModel[]> {
    const structured = data.map((item) => CreateData(LostItemModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all LostItem records
   */
  async purgeAllLostItem(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List LostItem records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listLostItem(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[LostItemModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get lost_item by Id index
   * This function gets data by index.
   */
  async getLostItemById(
    id: string,
  ): Promise<LostItemModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lost_item by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLostItemById(
    id: string,
    data: LostItemModel
  ): Promise<LostItemModel[]> {
    const index = createIndexId(
      id
    );

    const values = LostItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by Id index
   */
  async deleteLostItemById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lost_item by DataCreator index
   * This function gets data by index.
   */
  async getLostItemByDataCreator(
    data_creator: string,
  ): Promise<LostItemModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lost_item by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLostItemByDataCreator(
    data_creator: string,
    data: LostItemModel
  ): Promise<LostItemModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = LostItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by DataCreator index
   */
  async deleteLostItemByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lost_item by DataUpdater index
   * This function gets data by index.
   */
  async getLostItemByDataUpdater(
    data_updater: string,
  ): Promise<LostItemModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lost_item by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLostItemByDataUpdater(
    data_updater: string,
    data: LostItemModel
  ): Promise<LostItemModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = LostItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by DataUpdater index
   */
  async deleteLostItemByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lost_item by Category index
   * This function gets data by index.
   */
  async getLostItemByCategory(
    category: LostItemCategory,
  ): Promise<LostItemModel[]> {
    const index = createIndexCategory(
      category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lost_item by Category index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLostItemByCategory(
    category: LostItemCategory,
    data: LostItemModel
  ): Promise<LostItemModel[]> {
    const index = createIndexCategory(
      category
    );

    const values = LostItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by Category index
   */
  async deleteLostItemByCategory(
    category: LostItemCategory
  ): Promise<void> {
    const index = createIndexCategory(
      category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lost_item by Status index
   * This function gets data by index.
   */
  async getLostItemByStatus(
    status: LostItemStatus,
  ): Promise<LostItemModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lost_item by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLostItemByStatus(
    status: LostItemStatus,
    data: LostItemModel
  ): Promise<LostItemModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = LostItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by Status index
   */
  async deleteLostItemByStatus(
    status: LostItemStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lost_item by DateFound index
   * This function gets data by index.
   */
  async getLostItemByDateFound(
    date_found: string,
  ): Promise<LostItemModel[]> {
    const index = createIndexDateFound(
      date_found
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lost_item by DateFound index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLostItemByDateFound(
    date_found: string,
    data: LostItemModel
  ): Promise<LostItemModel[]> {
    const index = createIndexDateFound(
      date_found
    );

    const values = LostItemModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lost_item by DateFound index
   */
  async deleteLostItemByDateFound(
    date_found: string
  ): Promise<void> {
    const index = createIndexDateFound(
      date_found
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to LostItemModel data array
   */
  private resultToData(values: Data[]): LostItemModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return LostItemModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as LostItemModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized LostItemModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is LostItemModel => item !== null);
  }
}

/**
 * Convert LostItemModel data to Value array
 */
function LostItemModelToValues(data: LostItemModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'photo_url', type: DataType.string, defaultValue: null },
    { key: 'item_name', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'date_found', type: DataType.string, defaultValue: '' },
    { key: 'location_found', type: DataType.string, defaultValue: '' },
    { key: 'finder_name', type: DataType.string, defaultValue: null },
    { key: 'finder_email', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof LostItemModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to LostItemModel data
 */
function LostItemModelFromValues(values: Value[]): LostItemModel {
  const data: Partial<LostItemModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'photo_url':
        data.photo_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'item_name':
        data.item_name = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as LostItemCategory;
        break;
      case 'date_found':
        data.date_found = ParseValue(value, DataType.string) as string;
        break;
      case 'location_found':
        data.location_found = ParseValue(value, DataType.string) as string;
        break;
      case 'finder_name':
        data.finder_name = ParseValue(value, DataType.string) as string | null;
        break;
      case 'finder_email':
        data.finder_email = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as LostItemStatus;
        break;
    }
  }
  
  return data as LostItemModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Category fields
 */
function createIndexCategory(
  category: LostItemCategory
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, category, 'category'),
  ];

  return {
    fields: ['category'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: LostItemStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for DateFound fields
 */
function createIndexDateFound(
  date_found: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, date_found, 'date_found'),
  ];

  return {
    fields: ['date_found'],
    values
  };
}

export default LostItemORM;